# Generated by Django 5.0.6 on 2024-06-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filemanager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="base",
            name="path",
        ),
        migrations.AlterField(
            model_name="file",
            name="storage",
            field=models.FileField(upload_to=""),
        ),
    ]
