# Generated by Django 5.0.6 on 2024-06-11 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filemanager", "0002_remove_base_path_alter_file_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="filemanager.folder",
            ),
        ),
    ]
