# Generated by Django 5.0.6 on 2024-06-21 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filemanager", "0004_folder_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="base",
            name="lastmodified",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
